M48
; DRILL file {KiCad (6.0.6)} date Sun Aug 28 18:07:29 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-28T18:07:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.075Y-2.7
X4.075Y-5.769
X4.5603Y-3.7
X6.7496Y-3.7
X7.145Y-2.7
X7.145Y-5.765
T0
M30
